language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - pypy

install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install coverage --use-mirrors"
  - "pip install coveralls --use-mirrors"

script: 
  - nosetests

after_success:
  - coveralls

matrix:
  allow_failures:
    - python: 2.6
    - python: 3.2
    - python: pypy